/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const VendorId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingId = IDL.Text;
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'refunded' : IDL.Null,
  'partiallyPaid' : IDL.Null,
  'failed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const BookingStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'dispatched' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const UserId = IDL.Principal;
export const PackageId = IDL.Text;
export const Booking = IDL.Record({
  'id' : BookingId,
  'paymentStatus' : PaymentStatus,
  'guestCount' : IDL.Nat,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'bookingStatus' : BookingStatus,
  'cancellationFeePercent' : IDL.Nat,
  'advanceAmount' : IDL.Nat,
  'vendorId' : VendorId,
  'notes' : IDL.Opt(IDL.Text),
  'eventVenue' : IDL.Text,
  'customerId' : UserId,
  'stripePaymentIntentId' : IDL.Opt(IDL.Text),
  'totalPrice' : IDL.Nat,
  'packageId' : PackageId,
  'eventDate' : Timestamp,
});
export const CreateBookingRequest = IDL.Record({
  'guestCount' : IDL.Nat,
  'vendorId' : VendorId,
  'notes' : IDL.Opt(IDL.Text),
  'eventVenue' : IDL.Text,
  'packageId' : PackageId,
  'eventDate' : Timestamp,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const StallPackage = IDL.Record({
  'id' : PackageId,
  'name' : IDL.Text,
  'travelCharge' : IDL.Nat,
  'isActive' : IDL.Bool,
  'inclusions' : IDL.Vec(IDL.Text),
  'setupCharge' : IDL.Nat,
  'vendorId' : VendorId,
  'price' : IDL.Nat,
  'guestMax' : IDL.Nat,
  'guestMin' : IDL.Nat,
});
export const ReviewId = IDL.Text;
export const Review = IDL.Record({
  'id' : ReviewId,
  'bookingId' : BookingId,
  'createdAt' : Timestamp,
  'comment' : IDL.Text,
  'vendorId' : VendorId,
  'customerId' : UserId,
  'rating' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreateVendorRequest = IDL.Record({
  'serviceArea' : IDL.Text,
  'ownerName' : IDL.Text,
  'businessName' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'category' : IDL.Text,
  'phone' : IDL.Text,
  'photos' : IDL.Vec(ExternalBlob),
});
export const VendorStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'suspended' : IDL.Null,
});
export const Vendor = IDL.Record({
  'id' : VendorId,
  'serviceArea' : IDL.Text,
  'ownerName' : IDL.Text,
  'ownerId' : UserId,
  'createdAt' : Timestamp,
  'businessName' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'commissionRate' : IDL.Float64,
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
  'reviewCount' : IDL.Nat,
  'verificationStatus' : VendorStatus,
  'photos' : IDL.Vec(ExternalBlob),
});
export const AnalyticsSummary = IDL.Record({
  'commissionRevenue' : IDL.Nat,
  'cancelledBookings' : IDL.Nat,
  'totalBookings' : IDL.Nat,
  'completedBookings' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'totalCustomers' : IDL.Nat,
  'totalVendors' : IDL.Nat,
  'activeVendors' : IDL.Nat,
});
export const DateRangeResult = IDL.Record({
  'revenue' : IDL.Nat,
  'date' : Timestamp,
  'count' : IDL.Nat,
});
export const CancellationPolicy = IDL.Record({
  'tier1Days' : IDL.Nat,
  'tier1FeePercent' : IDL.Nat,
  'tier3FeePercent' : IDL.Nat,
  'tier2FeePercent' : IDL.Nat,
  'tier2Days' : IDL.Nat,
});
export const PlatformConfig = IDL.Record({
  'advancePaymentPercent' : IDL.Nat,
  'cancellationPolicy' : CancellationPolicy,
  'globalCommissionPercent' : IDL.Float64,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const BookingFilter = IDL.Record({
  'status' : IDL.Opt(BookingStatus),
  'toDate' : IDL.Opt(Timestamp),
  'vendorId' : IDL.Opt(VendorId),
  'fromDate' : IDL.Opt(Timestamp),
  'customerId' : IDL.Opt(UserId),
});
export const VendorFilter = IDL.Record({
  'serviceArea' : IDL.Opt(IDL.Text),
  'status' : IDL.Opt(VendorStatus),
  'featured' : IDL.Opt(IDL.Bool),
  'category' : IDL.Opt(IDL.Text),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateVendorRequest = IDL.Record({
  'serviceArea' : IDL.Opt(IDL.Text),
  'ownerName' : IDL.Opt(IDL.Text),
  'businessName' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'photos' : IDL.Opt(IDL.Vec(ExternalBlob)),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'approveVendor' : IDL.Func([VendorId, IDL.Float64], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateCancellationFee' : IDL.Func([BookingId], [IDL.Nat], ['query']),
  'cancelBooking' : IDL.Func([BookingId], [Booking], []),
  'confirmPayment' : IDL.Func([BookingId, IDL.Text], [Booking], []),
  'createBooking' : IDL.Func([CreateBookingRequest], [Booking], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createPackage' : IDL.Func(
      [
        VendorId,
        IDL.Record({
          'name' : IDL.Text,
          'travelCharge' : IDL.Nat,
          'inclusions' : IDL.Vec(IDL.Text),
          'setupCharge' : IDL.Nat,
          'price' : IDL.Nat,
          'guestMax' : IDL.Nat,
          'guestMin' : IDL.Nat,
        }),
      ],
      [StallPackage],
      [],
    ),
  'createReview' : IDL.Func([BookingId, IDL.Nat, IDL.Text], [Review], []),
  'createVendorProfile' : IDL.Func([CreateVendorRequest], [Vendor], []),
  'deletePackage' : IDL.Func([PackageId], [], []),
  'getAnalyticsSummary' : IDL.Func([], [AnalyticsSummary], ['query']),
  'getBooking' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
  'getBookingsByDateRange' : IDL.Func(
      [Timestamp, Timestamp],
      [IDL.Vec(DateRangeResult)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPackage' : IDL.Func([PackageId], [IDL.Opt(StallPackage)], ['query']),
  'getPlatformConfig' : IDL.Func([], [PlatformConfig], ['query']),
  'getRevenueByDateRange' : IDL.Func(
      [Timestamp, Timestamp],
      [IDL.Vec(DateRangeResult)],
      ['query'],
    ),
  'getReviewsByVendor' : IDL.Func([VendorId], [IDL.Vec(Review)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUnavailableDates' : IDL.Func([VendorId], [IDL.Vec(Timestamp)], ['query']),
  'getVendor' : IDL.Func([VendorId], [IDL.Opt(Vendor)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listBookings' : IDL.Func([BookingFilter], [IDL.Vec(Booking)], ['query']),
  'listPackagesByVendor' : IDL.Func(
      [VendorId],
      [IDL.Vec(StallPackage)],
      ['query'],
    ),
  'listVendors' : IDL.Func([VendorFilter], [IDL.Vec(Vendor)], ['query']),
  'markUnavailableDate' : IDL.Func([VendorId, Timestamp], [], []),
  'processRefund' : IDL.Func([BookingId], [], []),
  'rejectVendor' : IDL.Func([VendorId], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'sendBookingConfirmationEmail' : IDL.Func(
      [BookingId, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'sendCancellationEmail' : IDL.Func(
      [BookingId, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'sendNewBookingNotificationToVendor' : IDL.Func(
      [IDL.Text, IDL.Text, BookingId],
      [],
      [],
    ),
  'sendPaymentConfirmationEmail' : IDL.Func(
      [BookingId, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'sendVendorApprovalEmail' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'toggleFeatured' : IDL.Func([VendorId], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBookingStatus' : IDL.Func([BookingId, BookingStatus], [Booking], []),
  'updatePackage' : IDL.Func(
      [
        PackageId,
        IDL.Record({
          'name' : IDL.Opt(IDL.Text),
          'travelCharge' : IDL.Opt(IDL.Nat),
          'isActive' : IDL.Opt(IDL.Bool),
          'inclusions' : IDL.Opt(IDL.Vec(IDL.Text)),
          'setupCharge' : IDL.Opt(IDL.Nat),
          'price' : IDL.Opt(IDL.Nat),
          'guestMax' : IDL.Opt(IDL.Nat),
          'guestMin' : IDL.Opt(IDL.Nat),
        }),
      ],
      [StallPackage],
      [],
    ),
  'updatePlatformConfig' : IDL.Func([PlatformConfig], [], []),
  'updateVendorProfile' : IDL.Func(
      [VendorId, UpdateVendorRequest],
      [Vendor],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const VendorId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingId = IDL.Text;
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'refunded' : IDL.Null,
    'partiallyPaid' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const BookingStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'dispatched' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const PackageId = IDL.Text;
  const Booking = IDL.Record({
    'id' : BookingId,
    'paymentStatus' : PaymentStatus,
    'guestCount' : IDL.Nat,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'bookingStatus' : BookingStatus,
    'cancellationFeePercent' : IDL.Nat,
    'advanceAmount' : IDL.Nat,
    'vendorId' : VendorId,
    'notes' : IDL.Opt(IDL.Text),
    'eventVenue' : IDL.Text,
    'customerId' : UserId,
    'stripePaymentIntentId' : IDL.Opt(IDL.Text),
    'totalPrice' : IDL.Nat,
    'packageId' : PackageId,
    'eventDate' : Timestamp,
  });
  const CreateBookingRequest = IDL.Record({
    'guestCount' : IDL.Nat,
    'vendorId' : VendorId,
    'notes' : IDL.Opt(IDL.Text),
    'eventVenue' : IDL.Text,
    'packageId' : PackageId,
    'eventDate' : Timestamp,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const StallPackage = IDL.Record({
    'id' : PackageId,
    'name' : IDL.Text,
    'travelCharge' : IDL.Nat,
    'isActive' : IDL.Bool,
    'inclusions' : IDL.Vec(IDL.Text),
    'setupCharge' : IDL.Nat,
    'vendorId' : VendorId,
    'price' : IDL.Nat,
    'guestMax' : IDL.Nat,
    'guestMin' : IDL.Nat,
  });
  const ReviewId = IDL.Text;
  const Review = IDL.Record({
    'id' : ReviewId,
    'bookingId' : BookingId,
    'createdAt' : Timestamp,
    'comment' : IDL.Text,
    'vendorId' : VendorId,
    'customerId' : UserId,
    'rating' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreateVendorRequest = IDL.Record({
    'serviceArea' : IDL.Text,
    'ownerName' : IDL.Text,
    'businessName' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'category' : IDL.Text,
    'phone' : IDL.Text,
    'photos' : IDL.Vec(ExternalBlob),
  });
  const VendorStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const Vendor = IDL.Record({
    'id' : VendorId,
    'serviceArea' : IDL.Text,
    'ownerName' : IDL.Text,
    'ownerId' : UserId,
    'createdAt' : Timestamp,
    'businessName' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'commissionRate' : IDL.Float64,
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
    'reviewCount' : IDL.Nat,
    'verificationStatus' : VendorStatus,
    'photos' : IDL.Vec(ExternalBlob),
  });
  const AnalyticsSummary = IDL.Record({
    'commissionRevenue' : IDL.Nat,
    'cancelledBookings' : IDL.Nat,
    'totalBookings' : IDL.Nat,
    'completedBookings' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'totalCustomers' : IDL.Nat,
    'totalVendors' : IDL.Nat,
    'activeVendors' : IDL.Nat,
  });
  const DateRangeResult = IDL.Record({
    'revenue' : IDL.Nat,
    'date' : Timestamp,
    'count' : IDL.Nat,
  });
  const CancellationPolicy = IDL.Record({
    'tier1Days' : IDL.Nat,
    'tier1FeePercent' : IDL.Nat,
    'tier3FeePercent' : IDL.Nat,
    'tier2FeePercent' : IDL.Nat,
    'tier2Days' : IDL.Nat,
  });
  const PlatformConfig = IDL.Record({
    'advancePaymentPercent' : IDL.Nat,
    'cancellationPolicy' : CancellationPolicy,
    'globalCommissionPercent' : IDL.Float64,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const BookingFilter = IDL.Record({
    'status' : IDL.Opt(BookingStatus),
    'toDate' : IDL.Opt(Timestamp),
    'vendorId' : IDL.Opt(VendorId),
    'fromDate' : IDL.Opt(Timestamp),
    'customerId' : IDL.Opt(UserId),
  });
  const VendorFilter = IDL.Record({
    'serviceArea' : IDL.Opt(IDL.Text),
    'status' : IDL.Opt(VendorStatus),
    'featured' : IDL.Opt(IDL.Bool),
    'category' : IDL.Opt(IDL.Text),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateVendorRequest = IDL.Record({
    'serviceArea' : IDL.Opt(IDL.Text),
    'ownerName' : IDL.Opt(IDL.Text),
    'businessName' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'photos' : IDL.Opt(IDL.Vec(ExternalBlob)),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'approveVendor' : IDL.Func([VendorId, IDL.Float64], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateCancellationFee' : IDL.Func([BookingId], [IDL.Nat], ['query']),
    'cancelBooking' : IDL.Func([BookingId], [Booking], []),
    'confirmPayment' : IDL.Func([BookingId, IDL.Text], [Booking], []),
    'createBooking' : IDL.Func([CreateBookingRequest], [Booking], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createPackage' : IDL.Func(
        [
          VendorId,
          IDL.Record({
            'name' : IDL.Text,
            'travelCharge' : IDL.Nat,
            'inclusions' : IDL.Vec(IDL.Text),
            'setupCharge' : IDL.Nat,
            'price' : IDL.Nat,
            'guestMax' : IDL.Nat,
            'guestMin' : IDL.Nat,
          }),
        ],
        [StallPackage],
        [],
      ),
    'createReview' : IDL.Func([BookingId, IDL.Nat, IDL.Text], [Review], []),
    'createVendorProfile' : IDL.Func([CreateVendorRequest], [Vendor], []),
    'deletePackage' : IDL.Func([PackageId], [], []),
    'getAnalyticsSummary' : IDL.Func([], [AnalyticsSummary], ['query']),
    'getBooking' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
    'getBookingsByDateRange' : IDL.Func(
        [Timestamp, Timestamp],
        [IDL.Vec(DateRangeResult)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPackage' : IDL.Func([PackageId], [IDL.Opt(StallPackage)], ['query']),
    'getPlatformConfig' : IDL.Func([], [PlatformConfig], ['query']),
    'getRevenueByDateRange' : IDL.Func(
        [Timestamp, Timestamp],
        [IDL.Vec(DateRangeResult)],
        ['query'],
      ),
    'getReviewsByVendor' : IDL.Func([VendorId], [IDL.Vec(Review)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUnavailableDates' : IDL.Func(
        [VendorId],
        [IDL.Vec(Timestamp)],
        ['query'],
      ),
    'getVendor' : IDL.Func([VendorId], [IDL.Opt(Vendor)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listBookings' : IDL.Func([BookingFilter], [IDL.Vec(Booking)], ['query']),
    'listPackagesByVendor' : IDL.Func(
        [VendorId],
        [IDL.Vec(StallPackage)],
        ['query'],
      ),
    'listVendors' : IDL.Func([VendorFilter], [IDL.Vec(Vendor)], ['query']),
    'markUnavailableDate' : IDL.Func([VendorId, Timestamp], [], []),
    'processRefund' : IDL.Func([BookingId], [], []),
    'rejectVendor' : IDL.Func([VendorId], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'sendBookingConfirmationEmail' : IDL.Func(
        [BookingId, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'sendCancellationEmail' : IDL.Func(
        [BookingId, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'sendNewBookingNotificationToVendor' : IDL.Func(
        [IDL.Text, IDL.Text, BookingId],
        [],
        [],
      ),
    'sendPaymentConfirmationEmail' : IDL.Func(
        [BookingId, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'sendVendorApprovalEmail' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'toggleFeatured' : IDL.Func([VendorId], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBookingStatus' : IDL.Func([BookingId, BookingStatus], [Booking], []),
    'updatePackage' : IDL.Func(
        [
          PackageId,
          IDL.Record({
            'name' : IDL.Opt(IDL.Text),
            'travelCharge' : IDL.Opt(IDL.Nat),
            'isActive' : IDL.Opt(IDL.Bool),
            'inclusions' : IDL.Opt(IDL.Vec(IDL.Text)),
            'setupCharge' : IDL.Opt(IDL.Nat),
            'price' : IDL.Opt(IDL.Nat),
            'guestMax' : IDL.Opt(IDL.Nat),
            'guestMin' : IDL.Opt(IDL.Nat),
          }),
        ],
        [StallPackage],
        [],
      ),
    'updatePlatformConfig' : IDL.Func([PlatformConfig], [], []),
    'updateVendorProfile' : IDL.Func(
        [VendorId, UpdateVendorRequest],
        [Vendor],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };