/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsSummary {
  'commissionRevenue' : bigint,
  'vendorPayouts' : bigint,
  'cancelledBookings' : bigint,
  'totalBookings' : bigint,
  'topVendors' : Array<VendorBookingStat>,
  'completedBookings' : bigint,
  'totalRevenue' : bigint,
  'totalCustomers' : bigint,
  'totalVendors' : bigint,
  'activeVendors' : bigint,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Booking {
  'id' : BookingId,
  'paymentStatus' : PaymentStatus,
  'guestCount' : bigint,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'bookingStatus' : BookingStatus,
  'cancellationFeePercent' : bigint,
  'advanceAmount' : bigint,
  'vendorId' : VendorId,
  'notes' : [] | [string],
  'vendorPayout' : bigint,
  'commissionAmount' : bigint,
  'eventVenue' : string,
  'customerId' : UserId,
  'stripePaymentIntentId' : [] | [string],
  'totalPrice' : bigint,
  'packageId' : PackageId,
  'eventDate' : Timestamp,
}
export interface BookingFilter {
  'status' : [] | [BookingStatus],
  'toDate' : [] | [Timestamp],
  'vendorId' : [] | [VendorId],
  'fromDate' : [] | [Timestamp],
  'customerId' : [] | [UserId],
}
export type BookingId = string;
export type BookingStatus = { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'dispatched' : null } |
  { 'confirmed' : null };
export interface CancellationPolicy {
  'tier1Days' : bigint,
  'tier1FeePercent' : bigint,
  'tier3FeePercent' : bigint,
  'tier2FeePercent' : bigint,
  'tier2Days' : bigint,
}
export interface CategoryBreakdown {
  'categoryId' : string,
  'revenue' : bigint,
  'categoryName' : string,
  'bookingCount' : bigint,
}
export interface CreateBookingRequest {
  'guestCount' : bigint,
  'vendorId' : VendorId,
  'notes' : [] | [string],
  'eventVenue' : string,
  'packageId' : PackageId,
  'eventDate' : Timestamp,
}
export interface CreateVendorRequest {
  'serviceArea' : string,
  'ownerName' : string,
  'businessName' : string,
  'description' : string,
  'email' : string,
  'category' : string,
  'phone' : string,
  'photos' : Array<ExternalBlob>,
}
export interface DateRangeResult {
  'revenue' : bigint,
  'date' : Timestamp,
  'count' : bigint,
}
export type ExternalBlob = Uint8Array;
export type PackageId = string;
export interface PagedBookings {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<Booking>,
}
export interface PagedVendors {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<Vendor>,
}
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'refunded' : null } |
  { 'partiallyPaid' : null } |
  { 'failed' : null };
export interface PlatformConfig {
  'advancePaymentPercent' : bigint,
  'cancellationPolicy' : CancellationPolicy,
  'globalCommissionPercent' : number,
}
export interface Review {
  'id' : ReviewId,
  'bookingId' : BookingId,
  'createdAt' : Timestamp,
  'comment' : string,
  'vendorId' : VendorId,
  'customerId' : UserId,
  'rating' : bigint,
}
export type ReviewId = string;
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StallPackage {
  'id' : PackageId,
  'name' : string,
  'travelCharge' : bigint,
  'isActive' : boolean,
  'inclusions' : Array<string>,
  'setupCharge' : bigint,
  'vendorId' : VendorId,
  'price' : bigint,
  'guestMax' : bigint,
  'guestMin' : bigint,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateVendorRequest {
  'serviceArea' : [] | [string],
  'ownerName' : [] | [string],
  'businessName' : [] | [string],
  'description' : [] | [string],
  'email' : [] | [string],
  'category' : [] | [string],
  'phone' : [] | [string],
  'photos' : [] | [Array<ExternalBlob>],
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vendor {
  'id' : VendorId,
  'serviceArea' : string,
  'ownerName' : string,
  'ownerId' : UserId,
  'createdAt' : Timestamp,
  'businessName' : string,
  'description' : string,
  'email' : string,
  'isFeatured' : boolean,
  'category' : string,
  'commissionRate' : number,
  'rating' : number,
  'phone' : string,
  'reviewCount' : bigint,
  'verificationStatus' : VendorStatus,
  'photos' : Array<ExternalBlob>,
}
export interface VendorBookingStat {
  'revenue' : bigint,
  'vendorId' : VendorId,
  'vendorName' : string,
  'bookingCount' : bigint,
}
export interface VendorFilter {
  'serviceArea' : [] | [string],
  'status' : [] | [VendorStatus],
  'featured' : [] | [boolean],
  'category' : [] | [string],
}
export type VendorId = string;
export type VendorStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'suspended' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'approveVendor' : ActorMethod<[VendorId, number], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateCancellationFee' : ActorMethod<[BookingId], bigint>,
  'cancelBooking' : ActorMethod<[BookingId], Booking>,
  'confirmPayment' : ActorMethod<[BookingId, string], Booking>,
  'createBooking' : ActorMethod<[CreateBookingRequest], Booking>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createPackage' : ActorMethod<
    [
      VendorId,
      {
        'name' : string,
        'travelCharge' : bigint,
        'inclusions' : Array<string>,
        'setupCharge' : bigint,
        'price' : bigint,
        'guestMax' : bigint,
        'guestMin' : bigint,
      },
    ],
    StallPackage
  >,
  'createReview' : ActorMethod<[BookingId, bigint, string], Review>,
  'createVendorProfile' : ActorMethod<[CreateVendorRequest], Vendor>,
  'deletePackage' : ActorMethod<[PackageId], undefined>,
  'getAnalyticsSummary' : ActorMethod<[], AnalyticsSummary>,
  'getBooking' : ActorMethod<[BookingId], [] | [Booking]>,
  'getBookingsByDateRange' : ActorMethod<
    [Timestamp, Timestamp, [] | [string]],
    Array<DateRangeResult>
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryBreakdown' : ActorMethod<[], Array<CategoryBreakdown>>,
  'getPackage' : ActorMethod<[PackageId], [] | [StallPackage]>,
  'getPlatformConfig' : ActorMethod<[], PlatformConfig>,
  'getRevenueByDateRange' : ActorMethod<
    [Timestamp, Timestamp, [] | [string]],
    Array<DateRangeResult>
  >,
  'getReviewsByVendor' : ActorMethod<[VendorId], Array<Review>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUnavailableDates' : ActorMethod<[VendorId], Array<Timestamp>>,
  'getVendor' : ActorMethod<[VendorId], [] | [Vendor]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listBookings' : ActorMethod<[BookingFilter, bigint, bigint], PagedBookings>,
  'listPackagesByVendor' : ActorMethod<[VendorId], Array<StallPackage>>,
  'listVendors' : ActorMethod<[VendorFilter, bigint, bigint], PagedVendors>,
  'markUnavailableDate' : ActorMethod<[VendorId, Timestamp], undefined>,
  'processRefund' : ActorMethod<[BookingId], undefined>,
  'rejectVendor' : ActorMethod<[VendorId], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'sendBookingConfirmationEmail' : ActorMethod<
    [BookingId, string, string],
    undefined
  >,
  'sendCancellationEmail' : ActorMethod<
    [BookingId, string, string, bigint],
    undefined
  >,
  'sendNewBookingNotificationToVendor' : ActorMethod<
    [string, string, BookingId],
    undefined
  >,
  'sendPaymentConfirmationEmail' : ActorMethod<
    [BookingId, string, string, bigint],
    undefined
  >,
  'sendVendorApprovalEmail' : ActorMethod<[string, string, boolean], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'toggleFeatured' : ActorMethod<[VendorId], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBookingStatus' : ActorMethod<[BookingId, BookingStatus], Booking>,
  'updatePackage' : ActorMethod<
    [
      PackageId,
      {
        'name' : [] | [string],
        'travelCharge' : [] | [bigint],
        'isActive' : [] | [boolean],
        'inclusions' : [] | [Array<string>],
        'setupCharge' : [] | [bigint],
        'price' : [] | [bigint],
        'guestMax' : [] | [bigint],
        'guestMin' : [] | [bigint],
      },
    ],
    StallPackage
  >,
  'updatePlatformConfig' : ActorMethod<[PlatformConfig], undefined>,
  'updateVendorProfile' : ActorMethod<[VendorId, UpdateVendorRequest], Vendor>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];