/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface AnalyticsSummary {
    commissionRevenue: bigint;
    vendorPayouts: bigint;
    cancelledBookings: bigint;
    totalBookings: bigint;
    topVendors: Array<VendorBookingStat>;
    completedBookings: bigint;
    totalRevenue: bigint;
    totalCustomers: bigint;
    totalVendors: bigint;
    activeVendors: bigint;
}
export interface VendorFilter {
    serviceArea?: string;
    status?: VendorStatus;
    featured?: boolean;
    category?: string;
}
export interface PagedVendors {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<Vendor>;
}
export interface PlatformConfig {
    advancePaymentPercent: bigint;
    cancellationPolicy: CancellationPolicy;
    globalCommissionPercent: number;
}
export interface CancellationPolicy {
    tier1Days: bigint;
    tier1FeePercent: bigint;
    tier3FeePercent: bigint;
    tier2FeePercent: bigint;
    tier2Days: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface DateRangeResult {
    revenue: bigint;
    date: Timestamp;
    count: bigint;
}
export interface VendorBookingStat {
    revenue: bigint;
    vendorId: VendorId;
    vendorName: string;
    bookingCount: bigint;
}
export interface CategoryBreakdown {
    categoryId: string;
    revenue: bigint;
    categoryName: string;
    bookingCount: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type PackageId = string;
export interface StallPackage {
    id: PackageId;
    name: string;
    travelCharge: bigint;
    isActive: boolean;
    inclusions: Array<string>;
    setupCharge: bigint;
    vendorId: VendorId;
    price: bigint;
    guestMax: bigint;
    guestMin: bigint;
}
export interface BookingFilter {
    status?: BookingStatus;
    toDate?: Timestamp;
    vendorId?: VendorId;
    fromDate?: Timestamp;
    customerId?: UserId;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface Vendor {
    id: VendorId;
    serviceArea: string;
    ownerName: string;
    ownerId: UserId;
    createdAt: Timestamp;
    businessName: string;
    description: string;
    email: string;
    isFeatured: boolean;
    category: string;
    commissionRate: number;
    rating: number;
    phone: string;
    reviewCount: bigint;
    verificationStatus: VendorStatus;
    photos: Array<ExternalBlob>;
}
export type ReviewId = string;
export interface Review {
    id: ReviewId;
    bookingId: BookingId;
    createdAt: Timestamp;
    comment: string;
    vendorId: VendorId;
    customerId: UserId;
    rating: bigint;
}
export interface Booking {
    id: BookingId;
    paymentStatus: PaymentStatus;
    guestCount: bigint;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    bookingStatus: BookingStatus;
    cancellationFeePercent: bigint;
    advanceAmount: bigint;
    vendorId: VendorId;
    notes?: string;
    vendorPayout: bigint;
    commissionAmount: bigint;
    eventVenue: string;
    customerId: UserId;
    stripePaymentIntentId?: string;
    totalPrice: bigint;
    packageId: PackageId;
    eventDate: Timestamp;
}
export interface UpdateVendorRequest {
    serviceArea?: string;
    ownerName?: string;
    businessName?: string;
    description?: string;
    email?: string;
    category?: string;
    phone?: string;
    photos?: Array<ExternalBlob>;
}
export type BookingId = string;
export interface CreateBookingRequest {
    guestCount: bigint;
    vendorId: VendorId;
    notes?: string;
    eventVenue: string;
    packageId: PackageId;
    eventDate: Timestamp;
}
export interface CreateVendorRequest {
    serviceArea: string;
    ownerName: string;
    businessName: string;
    description: string;
    email: string;
    category: string;
    phone: string;
    photos: Array<ExternalBlob>;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type UserId = Principal;
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export type VendorId = string;
export interface PagedBookings {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<Booking>;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum BookingStatus {
    preparing = "preparing",
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    dispatched = "dispatched",
    confirmed = "confirmed"
}
export enum PaymentStatus {
    pending = "pending",
    paid = "paid",
    refunded = "refunded",
    partiallyPaid = "partiallyPaid",
    failed = "failed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VendorStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected",
    suspended = "suspended"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    approveVendor(vendorId: VendorId, commissionRate: number): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculateCancellationFee(bookingId: BookingId): Promise<bigint>;
    cancelBooking(bookingId: BookingId): Promise<Booking>;
    confirmPayment(bookingId: BookingId, paymentIntentId: string): Promise<Booking>;
    createBooking(req: CreateBookingRequest): Promise<Booking>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createPackage(vendorId: VendorId, pkg: {
        name: string;
        travelCharge: bigint;
        inclusions: Array<string>;
        setupCharge: bigint;
        price: bigint;
        guestMax: bigint;
        guestMin: bigint;
    }): Promise<StallPackage>;
    createReview(bookingId: BookingId, rating: bigint, comment: string): Promise<Review>;
    createVendorProfile(req: CreateVendorRequest): Promise<Vendor>;
    deletePackage(packageId: PackageId): Promise<void>;
    getAnalyticsSummary(): Promise<AnalyticsSummary>;
    getBooking(bookingId: BookingId): Promise<Booking | null>;
    getBookingsByDateRange(from: Timestamp, to: Timestamp, groupBy: string | null): Promise<Array<DateRangeResult>>;
    getCallerUserRole(): Promise<UserRole>;
    getCategoryBreakdown(): Promise<Array<CategoryBreakdown>>;
    getPackage(packageId: PackageId): Promise<StallPackage | null>;
    getPlatformConfig(): Promise<PlatformConfig>;
    getRevenueByDateRange(from: Timestamp, to: Timestamp, groupBy: string | null): Promise<Array<DateRangeResult>>;
    getReviewsByVendor(vendorId: VendorId): Promise<Array<Review>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUnavailableDates(vendorId: VendorId): Promise<Array<Timestamp>>;
    getVendor(vendorId: VendorId): Promise<Vendor | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listBookings(filter: BookingFilter, offset: bigint, limit: bigint): Promise<PagedBookings>;
    listPackagesByVendor(vendorId: VendorId): Promise<Array<StallPackage>>;
    listVendors(filter: VendorFilter, offset: bigint, limit: bigint): Promise<PagedVendors>;
    markUnavailableDate(vendorId: VendorId, date: Timestamp): Promise<void>;
    processRefund(bookingId: BookingId): Promise<void>;
    rejectVendor(vendorId: VendorId): Promise<void>;
    requestApproval(): Promise<void>;
    sendBookingConfirmationEmail(bookingId: BookingId, recipientEmail: string, customerName: string): Promise<void>;
    sendCancellationEmail(bookingId: BookingId, recipientEmail: string, customerName: string, refundAmount: bigint): Promise<void>;
    sendNewBookingNotificationToVendor(vendorEmail: string, vendorName: string, bookingId: BookingId): Promise<void>;
    sendPaymentConfirmationEmail(bookingId: BookingId, recipientEmail: string, customerName: string, amount: bigint): Promise<void>;
    sendVendorApprovalEmail(vendorEmail: string, vendorName: string, approved: boolean): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    toggleFeatured(vendorId: VendorId): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateBookingStatus(bookingId: BookingId, status: BookingStatus): Promise<Booking>;
    updatePackage(packageId: PackageId, pkg: {
        name?: string;
        travelCharge?: bigint;
        isActive?: boolean;
        inclusions?: Array<string>;
        setupCharge?: bigint;
        price?: bigint;
        guestMax?: bigint;
        guestMin?: bigint;
    }): Promise<StallPackage>;
    updatePlatformConfig(config: PlatformConfig): Promise<void>;
    updateVendorProfile(vendorId: VendorId, req: UpdateVendorRequest): Promise<Vendor>;
}
import type { ApprovalStatus as _ApprovalStatus, Booking as _Booking, BookingFilter as _BookingFilter, BookingId as _BookingId, BookingStatus as _BookingStatus, CreateBookingRequest as _CreateBookingRequest, CreateVendorRequest as _CreateVendorRequest, ExternalBlob as _ExternalBlob, PackageId as _PackageId, PagedBookings as _PagedBookings, PagedVendors as _PagedVendors, PaymentStatus as _PaymentStatus, StallPackage as _StallPackage, StripeSessionStatus as _StripeSessionStatus, Timestamp as _Timestamp, UpdateVendorRequest as _UpdateVendorRequest, UserApprovalInfo as _UserApprovalInfo, UserId as _UserId, UserRole as _UserRole, Vendor as _Vendor, VendorFilter as _VendorFilter, VendorId as _VendorId, VendorStatus as _VendorStatus, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async approveVendor(arg0: VendorId, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveVendor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveVendor(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateCancellationFee(arg0: BookingId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateCancellationFee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateCancellationFee(arg0);
            return result;
        }
    }
    async cancelBooking(arg0: BookingId): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return from_candid_Booking_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return from_candid_Booking_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async confirmPayment(arg0: BookingId, arg1: string): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmPayment(arg0, arg1);
                return from_candid_Booking_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmPayment(arg0, arg1);
            return from_candid_Booking_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBooking(arg0: CreateBookingRequest): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_CreateBookingRequest_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Booking_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_CreateBookingRequest_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Booking_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createPackage(arg0: VendorId, arg1: {
        name: string;
        travelCharge: bigint;
        inclusions: Array<string>;
        setupCharge: bigint;
        price: bigint;
        guestMax: bigint;
        guestMin: bigint;
    }): Promise<StallPackage> {
        if (this.processError) {
            try {
                const result = await this.actor.createPackage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPackage(arg0, arg1);
            return result;
        }
    }
    async createReview(arg0: BookingId, arg1: bigint, arg2: string): Promise<Review> {
        if (this.processError) {
            try {
                const result = await this.actor.createReview(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReview(arg0, arg1, arg2);
            return result;
        }
    }
    async createVendorProfile(arg0: CreateVendorRequest): Promise<Vendor> {
        if (this.processError) {
            try {
                const result = await this.actor.createVendorProfile(await to_candid_CreateVendorRequest_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Vendor_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVendorProfile(await to_candid_CreateVendorRequest_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Vendor_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePackage(arg0: PackageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePackage(arg0);
            return result;
        }
    }
    async getAnalyticsSummary(): Promise<AnalyticsSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsSummary();
            return result;
        }
    }
    async getBooking(arg0: BookingId): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByDateRange(arg0: Timestamp, arg1: Timestamp, arg2: string | null): Promise<Array<DateRangeResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByDateRange(arg0, arg1, to_candid_opt_n30(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByDateRange(arg0, arg1, to_candid_opt_n30(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategoryBreakdown(): Promise<Array<CategoryBreakdown>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryBreakdown();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryBreakdown();
            return result;
        }
    }
    async getPackage(arg0: PackageId): Promise<StallPackage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackage(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackage(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlatformConfig(): Promise<PlatformConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformConfig();
            return result;
        }
    }
    async getRevenueByDateRange(arg0: Timestamp, arg1: Timestamp, arg2: string | null): Promise<Array<DateRangeResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueByDateRange(arg0, arg1, to_candid_opt_n30(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueByDateRange(arg0, arg1, to_candid_opt_n30(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getReviewsByVendor(arg0: VendorId): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsByVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsByVendor(arg0);
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnavailableDates(arg0: VendorId): Promise<Array<Timestamp>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnavailableDates(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnavailableDates(arg0);
            return result;
        }
    }
    async getVendor(arg0: VendorId): Promise<Vendor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendor(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendor(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async listBookings(arg0: BookingFilter, arg1: bigint, arg2: bigint): Promise<PagedBookings> {
        if (this.processError) {
            try {
                const result = await this.actor.listBookings(to_candid_BookingFilter_n43(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_PagedBookings_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBookings(to_candid_BookingFilter_n43(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_PagedBookings_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPackagesByVendor(arg0: VendorId): Promise<Array<StallPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPackagesByVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPackagesByVendor(arg0);
            return result;
        }
    }
    async listVendors(arg0: VendorFilter, arg1: bigint, arg2: bigint): Promise<PagedVendors> {
        if (this.processError) {
            try {
                const result = await this.actor.listVendors(to_candid_VendorFilter_n50(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_PagedVendors_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVendors(to_candid_VendorFilter_n50(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_PagedVendors_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async markUnavailableDate(arg0: VendorId, arg1: Timestamp): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markUnavailableDate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markUnavailableDate(arg0, arg1);
            return result;
        }
    }
    async processRefund(arg0: BookingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.processRefund(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processRefund(arg0);
            return result;
        }
    }
    async rejectVendor(arg0: VendorId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectVendor(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async sendBookingConfirmationEmail(arg0: BookingId, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendBookingConfirmationEmail(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendBookingConfirmationEmail(arg0, arg1, arg2);
            return result;
        }
    }
    async sendCancellationEmail(arg0: BookingId, arg1: string, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendCancellationEmail(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendCancellationEmail(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async sendNewBookingNotificationToVendor(arg0: string, arg1: string, arg2: BookingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendNewBookingNotificationToVendor(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendNewBookingNotificationToVendor(arg0, arg1, arg2);
            return result;
        }
    }
    async sendPaymentConfirmationEmail(arg0: BookingId, arg1: string, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendPaymentConfirmationEmail(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendPaymentConfirmationEmail(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async sendVendorApprovalEmail(arg0: string, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendVendorApprovalEmail(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendVendorApprovalEmail(arg0, arg1, arg2);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n57(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n57(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async toggleFeatured(arg0: VendorId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleFeatured(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleFeatured(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBookingStatus(arg0: BookingId, arg1: BookingStatus): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n45(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Booking_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n45(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Booking_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePackage(arg0: PackageId, arg1: {
        name?: string;
        travelCharge?: bigint;
        isActive?: boolean;
        inclusions?: Array<string>;
        setupCharge?: bigint;
        price?: bigint;
        guestMax?: bigint;
        guestMin?: bigint;
    }): Promise<StallPackage> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePackage(arg0, to_candid_record_n59(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePackage(arg0, to_candid_record_n59(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePlatformConfig(arg0: PlatformConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlatformConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlatformConfig(arg0);
            return result;
        }
    }
    async updateVendorProfile(arg0: VendorId, arg1: UpdateVendorRequest): Promise<Vendor> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVendorProfile(arg0, await to_candid_UpdateVendorRequest_n60(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Vendor_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVendorProfile(arg0, await to_candid_UpdateVendorRequest_n60(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Vendor_n23(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ApprovalStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_PagedBookings_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PagedBookings): PagedBookings {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
async function from_candid_PagedVendors_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PagedVendors): Promise<PagedVendors> {
    return await from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_VendorStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VendorStatus): VendorStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_Vendor_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Vendor): Promise<Vendor> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StallPackage]): StallPackage | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Vendor]): Promise<Vendor | null> {
    return value.length === 0 ? null : await from_candid_Vendor_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BookingId;
    paymentStatus: _PaymentStatus;
    guestCount: bigint;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    bookingStatus: _BookingStatus;
    cancellationFeePercent: bigint;
    advanceAmount: bigint;
    vendorId: _VendorId;
    notes: [] | [string];
    vendorPayout: bigint;
    commissionAmount: bigint;
    eventVenue: string;
    customerId: _UserId;
    stripePaymentIntentId: [] | [string];
    totalPrice: bigint;
    packageId: _PackageId;
    eventDate: _Timestamp;
}): {
    id: BookingId;
    paymentStatus: PaymentStatus;
    guestCount: bigint;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    bookingStatus: BookingStatus;
    cancellationFeePercent: bigint;
    advanceAmount: bigint;
    vendorId: VendorId;
    notes?: string;
    vendorPayout: bigint;
    commissionAmount: bigint;
    eventVenue: string;
    customerId: UserId;
    stripePaymentIntentId?: string;
    totalPrice: bigint;
    packageId: PackageId;
    eventDate: Timestamp;
} {
    return {
        id: value.id,
        paymentStatus: from_candid_PaymentStatus_n12(_uploadFile, _downloadFile, value.paymentStatus),
        guestCount: value.guestCount,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        bookingStatus: from_candid_BookingStatus_n14(_uploadFile, _downloadFile, value.bookingStatus),
        cancellationFeePercent: value.cancellationFeePercent,
        advanceAmount: value.advanceAmount,
        vendorId: value.vendorId,
        notes: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.notes)),
        vendorPayout: value.vendorPayout,
        commissionAmount: value.commissionAmount,
        eventVenue: value.eventVenue,
        customerId: value.customerId,
        stripePaymentIntentId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.stripePaymentIntentId)),
        totalPrice: value.totalPrice,
        packageId: value.packageId,
        eventDate: value.eventDate
    };
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VendorId;
    serviceArea: string;
    ownerName: string;
    ownerId: _UserId;
    createdAt: _Timestamp;
    businessName: string;
    description: string;
    email: string;
    isFeatured: boolean;
    category: string;
    commissionRate: number;
    rating: number;
    phone: string;
    reviewCount: bigint;
    verificationStatus: _VendorStatus;
    photos: Array<_ExternalBlob>;
}): Promise<{
    id: VendorId;
    serviceArea: string;
    ownerName: string;
    ownerId: UserId;
    createdAt: Timestamp;
    businessName: string;
    description: string;
    email: string;
    isFeatured: boolean;
    category: string;
    commissionRate: number;
    rating: number;
    phone: string;
    reviewCount: bigint;
    verificationStatus: VendorStatus;
    photos: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        serviceArea: value.serviceArea,
        ownerName: value.ownerName,
        ownerId: value.ownerId,
        createdAt: value.createdAt,
        businessName: value.businessName,
        description: value.description,
        email: value.email,
        isFeatured: value.isFeatured,
        category: value.category,
        commissionRate: value.commissionRate,
        rating: value.rating,
        phone: value.phone,
        reviewCount: value.reviewCount,
        verificationStatus: from_candid_VendorStatus_n25(_uploadFile, _downloadFile, value.verificationStatus),
        photos: await from_candid_vec_n27(_uploadFile, _downloadFile, value.photos)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n41(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<_Booking>;
}): {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<Booking>;
} {
    return {
        total: value.total,
        offset: value.offset,
        limit: value.limit,
        items: from_candid_vec_n49(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<_Vendor>;
}): Promise<{
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<Vendor>;
}> {
    return {
        total: value.total,
        offset: value.offset,
        limit: value.limit,
        items: await from_candid_vec_n56(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    refunded: null;
} | {
    partiallyPaid: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "paid" in value ? PaymentStatus.paid : "refunded" in value ? PaymentStatus.refunded : "partiallyPaid" in value ? PaymentStatus.partiallyPaid : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preparing: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    dispatched: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "preparing" in value ? BookingStatus.preparing : "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "completed" in value ? BookingStatus.completed : "dispatched" in value ? BookingStatus.dispatched : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    suspended: null;
}): VendorStatus {
    return "pending" in value ? VendorStatus.pending : "approved" in value ? VendorStatus.approved : "rejected" in value ? VendorStatus.rejected : "suspended" in value ? VendorStatus.suspended : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n36(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n10(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Vendor>): Promise<Array<Vendor>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Vendor_n23(_uploadFile, _downloadFile, x)));
}
function to_candid_ApprovalStatus_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function to_candid_BookingFilter_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingFilter): _BookingFilter {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_BookingStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function to_candid_CreateBookingRequest_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateBookingRequest): _CreateBookingRequest {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function to_candid_CreateVendorRequest_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateVendorRequest): Promise<_CreateVendorRequest> {
    return await to_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_UpdateVendorRequest_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateVendorRequest): Promise<_UpdateVendorRequest> {
    return await to_candid_record_n61(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_VendorFilter_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VendorFilter): _VendorFilter {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_VendorStatus_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VendorStatus): _VendorStatus {
    return to_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    guestCount: bigint;
    vendorId: VendorId;
    notes?: string;
    eventVenue: string;
    packageId: PackageId;
    eventDate: Timestamp;
}): {
    guestCount: bigint;
    vendorId: _VendorId;
    notes: [] | [string];
    eventVenue: string;
    packageId: _PackageId;
    eventDate: _Timestamp;
} {
    return {
        guestCount: value.guestCount,
        vendorId: value.vendorId,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        eventVenue: value.eventVenue,
        packageId: value.packageId,
        eventDate: value.eventDate
    };
}
async function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceArea: string;
    ownerName: string;
    businessName: string;
    description: string;
    email: string;
    category: string;
    phone: string;
    photos: Array<ExternalBlob>;
}): Promise<{
    serviceArea: string;
    ownerName: string;
    businessName: string;
    description: string;
    email: string;
    category: string;
    phone: string;
    photos: Array<_ExternalBlob>;
}> {
    return {
        serviceArea: value.serviceArea,
        ownerName: value.ownerName,
        businessName: value.businessName,
        description: value.description,
        email: value.email,
        category: value.category,
        phone: value.phone,
        photos: await to_candid_vec_n21(_uploadFile, _downloadFile, value.photos)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: BookingStatus;
    toDate?: Timestamp;
    vendorId?: VendorId;
    fromDate?: Timestamp;
    customerId?: UserId;
}): {
    status: [] | [_BookingStatus];
    toDate: [] | [_Timestamp];
    vendorId: [] | [_VendorId];
    fromDate: [] | [_Timestamp];
    customerId: [] | [_UserId];
} {
    return {
        status: value.status ? candid_some(to_candid_BookingStatus_n45(_uploadFile, _downloadFile, value.status)) : candid_none(),
        toDate: value.toDate ? candid_some(value.toDate) : candid_none(),
        vendorId: value.vendorId ? candid_some(value.vendorId) : candid_none(),
        fromDate: value.fromDate ? candid_some(value.fromDate) : candid_none(),
        customerId: value.customerId ? candid_some(value.customerId) : candid_none()
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceArea?: string;
    status?: VendorStatus;
    featured?: boolean;
    category?: string;
}): {
    serviceArea: [] | [string];
    status: [] | [_VendorStatus];
    featured: [] | [boolean];
    category: [] | [string];
} {
    return {
        serviceArea: value.serviceArea ? candid_some(value.serviceArea) : candid_none(),
        status: value.status ? candid_some(to_candid_VendorStatus_n52(_uploadFile, _downloadFile, value.status)) : candid_none(),
        featured: value.featured ? candid_some(value.featured) : candid_none(),
        category: value.category ? candid_some(value.category) : candid_none()
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name?: string;
    travelCharge?: bigint;
    isActive?: boolean;
    inclusions?: Array<string>;
    setupCharge?: bigint;
    price?: bigint;
    guestMax?: bigint;
    guestMin?: bigint;
}): {
    name: [] | [string];
    travelCharge: [] | [bigint];
    isActive: [] | [boolean];
    inclusions: [] | [Array<string>];
    setupCharge: [] | [bigint];
    price: [] | [bigint];
    guestMax: [] | [bigint];
    guestMin: [] | [bigint];
} {
    return {
        name: value.name ? candid_some(value.name) : candid_none(),
        travelCharge: value.travelCharge ? candid_some(value.travelCharge) : candid_none(),
        isActive: value.isActive ? candid_some(value.isActive) : candid_none(),
        inclusions: value.inclusions ? candid_some(value.inclusions) : candid_none(),
        setupCharge: value.setupCharge ? candid_some(value.setupCharge) : candid_none(),
        price: value.price ? candid_some(value.price) : candid_none(),
        guestMax: value.guestMax ? candid_some(value.guestMax) : candid_none(),
        guestMin: value.guestMin ? candid_some(value.guestMin) : candid_none()
    };
}
async function to_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceArea?: string;
    ownerName?: string;
    businessName?: string;
    description?: string;
    email?: string;
    category?: string;
    phone?: string;
    photos?: Array<ExternalBlob>;
}): Promise<{
    serviceArea: [] | [string];
    ownerName: [] | [string];
    businessName: [] | [string];
    description: [] | [string];
    email: [] | [string];
    category: [] | [string];
    phone: [] | [string];
    photos: [] | [Array<_ExternalBlob>];
}> {
    return {
        serviceArea: value.serviceArea ? candid_some(value.serviceArea) : candid_none(),
        ownerName: value.ownerName ? candid_some(value.ownerName) : candid_none(),
        businessName: value.businessName ? candid_some(value.businessName) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none(),
        category: value.category ? candid_some(value.category) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none(),
        photos: value.photos ? candid_some(await to_candid_vec_n21(_uploadFile, _downloadFile, value.photos)) : candid_none()
    };
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    preparing: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    dispatched: null;
} | {
    confirmed: null;
} {
    return value == BookingStatus.preparing ? {
        preparing: null
    } : value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value == BookingStatus.dispatched ? {
        dispatched: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VendorStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    suspended: null;
} {
    return value == VendorStatus.pending ? {
        pending: null
    } : value == VendorStatus.approved ? {
        approved: null
    } : value == VendorStatus.rejected ? {
        rejected: null
    } : value == VendorStatus.suspended ? {
        suspended: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n22(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
